In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect("module6_lab2.db")
cur = con.cursor()

print("Database connected")

Database connected

In [2]:
cur.execute("""
CREATE TABLE IF NOT EXISTS customers (
    id INTEGER PRIMARY KEY,
    name TEXT,
    city TEXT,
    total_spent REAL
)
""")

con.commit()

print("Customers table created")

Customers table created

### MySQL to SQLite Note

SQLite uses a simpler data type system than MySQL. I used INTEGER, TEXT, and REAL data types when creating the customers table.

In [3]:
customers = [
    (1, "Olivia", "San Diego", 125.50),
    (2, "Ethan", "Sacramento", 210.75),
    (3, "Chloe", "San Francisco", 89.99),
    (4, "Noah", "Fresno", 340.20),
    (5, "Grace", "San Jose", 175.00),
    (6, "Lucas", "Riverside", 95.40),
    (7, "Mia", "Anaheim", 260.30),
    (8, "Henry", "Santa Barbara", 145.80)
]

cur.executemany("""
INSERT OR REPLACE INTO customers (id, name, city, total_spent)
VALUES (?, ?, ?, ?)
""", customers)

con.commit()

print("8 customers inserted")

8 customers inserted

In [4]:
df = pd.read_sql_query("SELECT * FROM customers", con)
df

   id    name           city  total_spent
0   1  Olivia      San Diego       125.50
1   2   Ethan     Sacramento       210.75
2   3   Chloe  San Francisco        89.99
3   4    Noah         Fresno       340.20
4   5   Grace       San Jose       175.00
5   6   Lucas      Riverside        95.40
6   7     Mia        Anaheim       260.30
7   8   Henry  Santa Barbara       145.80

### MySQL to SQLite Note

SQLite uses a simpler data type system than MySQL. I used INTEGER, TEXT, and REAL data types when creating the customers table.

In [5]:
# Query 1: WHERE
query1 = """
SELECT *
FROM customers
WHERE total_spent > 150;
"""

result1 = pd.read_sql_query(query1, con)
result1

   id   name        city  total_spent
0   2  Ethan  Sacramento       210.75
1   4   Noah      Fresno       340.20
2   5  Grace    San Jose       175.00
3   7    Mia     Anaheim       260.30

In [6]:
# Query 2: ORDER BY
query2 = """
SELECT *
FROM customers
ORDER BY total_spent DESC;
"""

result2 = pd.read_sql_query(query2, con)
result2

   id    name           city  total_spent
0   4    Noah         Fresno       340.20
1   7     Mia        Anaheim       260.30
2   2   Ethan     Sacramento       210.75
3   5   Grace       San Jose       175.00
4   8   Henry  Santa Barbara       145.80
5   1  Olivia      San Diego       125.50
6   6   Lucas      Riverside        95.40
7   3   Chloe  San Francisco        89.99

In [7]:
# Query 3: LIKE
query3 = """
SELECT *
FROM customers
WHERE name LIKE '%a%';
"""

result3 = pd.read_sql_query(query3, con)
result3

   id    name        city  total_spent
0   1  Olivia   San Diego       125.50
1   2   Ethan  Sacramento       210.75
2   4    Noah      Fresno       340.20
3   5   Grace    San Jose       175.00
4   6   Lucas   Riverside        95.40
5   7     Mia     Anaheim       260.30

In [ ]:
import matplotlib.pyplot as plt

# Chart from Query 2 result
plt.figure(figsize=(8, 5))
plt.bar(result2["name"], result2["total_spent"])

plt.title("Total Spending by Customer")
plt.xlabel("Customer")
plt.ylabel("Total Spent ($)")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()